parameters:
#    selly_cdn_serve_images_test.example.class: Selly\CdnServeImages\TestBundle\Example

services:
#    selly_cdn_serve_images_test.example:
#        class: %selly_cdn_serve_images_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
